In [2]:
import torch
print(torch.__version__)  # Check if PyTorch is installed
print(torch.cuda.is_available())  # Check if GPU is detected

2.6.0+cu126
True


In [8]:
#Initializing Tensor
device = "cuda" if torch.cuda.is_available() else "cpu"

my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype = torch.float32, device = device, requires_grad = True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [10]:
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

torch.float32
cuda:0
torch.Size([2, 3])
True


In [9]:
#Other common initialization methods
x = torch.empty(size = (3, 3))
print(x)
y = torch.zeros((3, 3))
print(y)
z = torch.rand((3, 3))
print(z)
w = torch.eye(5, 5)
print(w)
v = torch.arange(start = 0, end = 5, step = 1)
print(v)

tensor([[-4.5868e-08,  2.0137e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.5494, 0.3807, 0.8434],
        [0.4763, 0.9362, 0.1519],
        [0.0748, 0.4726, 0.6362]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4])


In [21]:
#Converting between tensor types
tensor = torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [25]:
#Array to Tensor conversion
import numpy as np
np_array = np.zeros((5, 5))
print(np_array)
tensor = torch.from_numpy(np_array)
print(tensor)
np_array_back = tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
#Tensor math and Comparison operator
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

#Addition
z1 = torch.empty(3)
torch.add(x, y, out = z1)
print(z1)

z2 = torch.add(x, y)

z = x + y
print(z)

#Subtraction
z = x - y
print(z)

#Division
z = torch.true_divide(x, y)
print(z)

#Inplace operations
t = torch.zeros(3)
t.add_(x)
t += x #t = t + x <-- this creates a copy of t and hence the operation isn't inplace
print(t)

#Exponentiation
z = x.pow(2)
z = x ** 2
print(z)

#Simple comparison
z = x > 0
print(z)

#Matrix multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))

x3 = torch.mm(x1, x2) #shape would be 2 x 3
x3 = x1.mm(x2)
print(x3)

#Matrix exponentiation
matrix_exp = torch.rand(5, 5)
print(matrix_exp.matrix_power(3))

#Element wise multiplication
z = x * y
print(z)

#dot product
z = torch.dot(x, y)
print(z)

#Batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))

out_bmm = torch.bmm(tensor1, tensor2) 

tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([-8, -6, -4])
tensor([0.1111, 0.2500, 0.4286])
tensor([2., 4., 6.])
tensor([1, 4, 9])
tensor([True, True, True])
tensor([[2.1601, 2.2817, 3.4343],
        [1.2430, 1.3198, 2.5610]])
tensor([[3.3586, 1.7667, 1.2434, 1.3738, 1.7623],
        [1.5543, 0.8662, 0.6081, 0.6353, 0.7941],
        [3.0568, 1.5117, 1.1704, 1.3805, 1.6699],
        [2.8419, 1.5403, 1.1007, 1.2171, 1.4453],
        [3.3845, 1.7974, 1.3140, 1.4551, 1.8177]])
tensor([ 9, 16, 21])
tensor(46)


In [7]:
#Example of Broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2
print(z)

z = x1 ** x2 #the rows adjust themselfs <-- reason why it's called broadcasting
print(z)

tensor([[-0.4148,  0.6008,  0.0733, -0.1555,  0.1298],
        [-0.8209,  0.9005,  0.1169, -0.2229, -0.2370],
        [-0.6458,  0.5195, -0.1760,  0.1505, -0.1101],
        [-0.6717,  0.9192,  0.1840,  0.0608, -0.3946],
        [ 0.0691,  0.9223,  0.1007, -0.3894,  0.2340]])
tensor([[0.5064, 0.9723, 0.8502, 0.6977, 0.7826],
        [0.0767, 0.9979, 0.8836, 0.6385, 0.4988],
        [0.2748, 0.9635, 0.6482, 0.9522, 0.6154],
        [0.2473, 0.9993, 0.9342, 0.8797, 0.2732],
        [0.9499, 0.9995, 0.8713, 0.4851, 0.8431]])


In [12]:
#Useful tensor operations
sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
abs_x = torch.abs(x)
z = torch.argmax(x, dim=0)
z = torch.argmin(x, dim=0)
mean_x = torch.mean(x.float(), dim=0)
z = torch.eq(x, y)
sorted_y, indices = torch.sort(y, dim=0, descending=False)

z = torch.clamp(x, min=0, max=10) #sets any value below 0 to be 0, and any value above 10 to be 10

x = torch.tensor([1, 0, 1, 1], dtype = torch.bool)
z = torch.any(x) #this is true for all
z = torch.all(x) #for this to be true, all values in the tensor should be 1

In [ ]:
#Tensor Indexing
